export * from './HomeTemplate';
export * from './ContactTemplate';
export * from './BasicTemplate';
export * from './IndexTemplate';
export * from './LoginTemplate';
export * from './PaymentTemplate';
export * from './SignupTemplate';
export * from './ForgotPasswordTemplate';
export * from './ResetPasswordTemplate';